import { useEffect, useState } from 'react'
import { Link, useParams, useSearch } from '@tanstack/react-router'
import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, Cable, CircleAlert, KeyRound, RefreshCw, Search, Settings2, Workflow } from 'lucide-react'
import { adaptersAPI } from '@/api'
import { adaptersQuery, qk, workflowsQuery } from '@/api/queries'
import { SchemaForm } from '@/components/schema-form'
import { PageHeading } from '@/components/page-heading'
import { StatusBadge } from '@/components/status-badge'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Confirm } from '@/components/ui/confirm'
import { EmptyState, ErrorState, LoadingState } from '@/components/query-state'
import { Input } from '@/components/ui/input'
import { useToast } from '@/components/ui/use-toast'
import { formatDate, resourceLabel } from '@/lib/utils'
import { supportsCapability } from '@/lib/capabilities'
import { ResourceBreadcrumbs } from '@/components/adapter/resource-breadcrumbs'
import { errorMessage } from '@/lib/errors'
import type { Resource, ResourceRef } from '@/types/api'
import { AdapterMark } from '@/components/adapter/adapter-mark'
import { PluginTrustBadges } from '@/components/plugin-trust'
import { adapterStateLabel, workflowStateLabel } from '@/lib/labels'

type Tab = 'overview' | 'settings' | 'resources' | 'workflows'
export function AdapterDetailPage() {
  const { adapterId } = useParams({ from: '/adapters/$adapterId' }); const routeSearch = useSearch({ from: '/adapters/$adapterId' }); const client = useQueryClient(); const { toast } = useToast()
  const [tab, setTab] = useState<Tab>(routeSearch.tab ?? 'overview'); const [resource, setResource] = useState<ResourceRef>(); const [q, setQ] = useState(''); const [resourceType, setResourceType] = useState(''); const [searchTerm, setSearchTerm] = useState('')
  const adapter = useQuery({ queryKey: qk.adapter(adapterId), queryFn: () => adaptersAPI.get(adapterId) })
  const list = useQuery(adaptersQuery); const current = adapter.data ?? list.data?.find(item => item.status.id === adapterId); const descriptor = current?.descriptor
  const config = useQuery({ queryKey: qk.config(adapterId, resource), queryFn: () => adaptersAPI.config(adapterId, resource), enabled: Boolean(descriptor && tab === 'settings'), retry: false })
  const workflows = useQuery(workflowsQuery); const canBrowse = supportsCapability(current, 'resource_browse')
  useEffect(() => { if (routeSearch.tab === 'resources' && canBrowse) setTab('resources'); else if (!adapter.isLoading && !canBrowse && tab === 'resources') setTab('overview') }, [adapter.isLoading, canBrowse, routeSearch.tab, tab])
  const resources = useInfiniteQuery({ queryKey: qk.resources(adapterId, { q: searchTerm, resource, resourceType }), queryFn: ({ pageParam }) => adaptersAPI.resources(adapterId, { q: searchTerm || undefined, parent: resource, resource_type: resourceType || undefined, cursor: pageParam, limit: 20 }), initialPageParam: undefined as string | undefined, getNextPageParam: page => page.next_cursor, enabled: Boolean(canBrowse && tab === 'resources' && descriptor), retry: false })
  const controls = useMutation({ mutationFn: (action: 'restart' | 'enable' | 'disable') => adaptersAPI.action(adapterId, action), onSuccess: result => { toast(`어댑터 상태: ${adapterStateLabel(result.status.state)}`); void client.invalidateQueries({ queryKey: qk.adapters }); void client.invalidateQueries({ queryKey: qk.adapter(adapterId) }) }, onError: error => toast('어댑터 작업 실패', errorMessage(error), 'error') })
  const save = useMutation({ mutationFn: (body: { values: Record<string, unknown>; secrets: Record<string, string>; clear_values: string[]; clear_secrets: string[] }) => adaptersAPI.saveConfig(adapterId, { ...body, resource }), onSuccess: () => { toast('설정을 저장했습니다.'); void client.invalidateQueries({ queryKey: qk.config(adapterId, resource) }) }, onError: error => toast('설정 저장 실패', errorMessage(error), 'error') })
  const allResourceTypes = descriptor?.resource_types ?? []
  const adapterWorkflows = workflows.data?.filter(item => item.adapter_id === adapterId) ?? []
  const resourceItems = resources.data?.pages.flatMap(page => page.items) ?? []
  if (adapter.isLoading) return <LoadingState />
  if (adapter.error || !current) return <ErrorState message={errorMessage(adapter.error ?? '어댑터를 찾을 수 없습니다.')} retry={() => void adapter.refetch()} />
  const restarting = current.status.state === 'restarting'
  const controlsBusy = controls.isPending || restarting
  const canRestart = Boolean(descriptor) && current.status.state !== 'disabled' && current.status.state !== 'rejected' && !controlsBusy
  const canEnable = Boolean(descriptor) && current.status.state === 'disabled' && !controlsBusy
  const canDisable = Boolean(descriptor) && current.status.state !== 'disabled' && current.status.state !== 'rejected' && !controlsBusy
  const tabs: { key: Tab; label: string; icon: typeof Cable; unavailable?: boolean }[] = [{ key: 'overview', label: '개요', icon: Cable }, { key: 'settings', label: '설정', icon: Settings2 }, { key: 'resources', label: '리소스', icon: Search, unavailable: !canBrowse }, { key: 'workflows', label: '워크플로', icon: Workflow }]
  return <div className="page-enter"><PageHeading eyebrow="어댑터 상세" title={<span className="flex min-w-0 items-center gap-3"><AdapterMark adapter={current} size="lg" /><span className="min-w-0 truncate">{descriptor?.name ?? current.status.name ?? adapterId}</span></span>} description={`${adapterId} · ${descriptor?.version ?? current.status.version ?? '버전 미보고'} · 프로토콜 v${descriptor?.protocol_version ?? current.status.protocol_version ?? '—'}`} actions={<>
    <Link to="/adapters"><Button variant="outline" size="sm"><ArrowLeft className="h-4 w-4" />목록</Button></Link>{descriptor && <>
    <Confirm trigger={<Button variant="outline" size="sm" disabled={!canRestart}><RefreshCw className="h-4 w-4" />{restarting ? '재시작 중…' : '재시작'}</Button>} title="어댑터 프로세스를 재시작할까요?" description="현재 어댑터 워크플로는 종료될 수 있습니다. 이미 확인된 녹화는 계속 수집합니다." confirmLabel="재시작" onConfirm={() => controls.mutate('restart')} disabled={!canRestart} />
    {current.status.state === 'disabled' ? <Confirm trigger={<Button size="sm" disabled={!canEnable}>활성화</Button>} title="어댑터를 활성화할까요?" description="활성화하면 새 녹화 확인에 이 어댑터를 사용할 수 있습니다." confirmLabel="활성화" onConfirm={() => controls.mutate('enable')} disabled={!canEnable} /> : <Confirm trigger={<Button variant="destructive" size="sm" disabled={!canDisable}>비활성화</Button>} title="어댑터를 비활성화할까요?" description="새 녹화 확인이 차단됩니다. 이미 확인된 녹화는 영향을 받지 않습니다." confirmLabel="비활성화" destructive onConfirm={() => controls.mutate('disable')} disabled={!canDisable} />}
    </>}</>} />
    <div className="mb-4 flex gap-1 overflow-x-auto border-b border-border" role="tablist" aria-label="어댑터 상세 화면">{tabs.filter(item => !item.unavailable).map(item => <button key={item.key} id={`adapter-tab-${item.key}`} aria-controls={`adapter-panel-${item.key}`} role="tab" aria-selected={tab === item.key} tabIndex={tab === item.key ? 0 : -1} onClick={() => setTab(item.key)} className={`focus-ring inline-flex min-w-max items-center gap-2 border-b-2 px-3 py-2.5 text-sm ${tab === item.key ? 'border-primary font-semibold text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'}`}><item.icon className="h-4 w-4" />{item.label}</button>)}</div>
    {tab === 'overview' && <div role="tabpanel" id="adapter-panel-overview" aria-labelledby="adapter-tab-overview" tabIndex={0} className="grid gap-4 xl:grid-cols-[1fr_.75fr]"><Card><CardHeader><CardTitle>어댑터 정보</CardTitle></CardHeader><CardContent><div className="grid grid-cols-2 gap-x-4 gap-y-3 sm:grid-cols-3">{[['ID', descriptor?.id ?? current.status.id], ['이름', descriptor?.name ?? current.status.name ?? '—'], ['버전', descriptor?.version ?? current.status.version ?? '—'], ['프로토콜', `v${descriptor?.protocol_version ?? current.status.protocol_version ?? '—'}`], ['세대', current.status.generation ?? '—'], ['재시작 횟수', current.status.restart_attempts ?? 0]].map(([label, value]) => <Info key={String(label)} label={String(label)} value={String(value)} />)}</div><div className="mt-4 border-t border-border pt-3"><p className="text-xs font-semibold">배포 경로와 게시자</p><div className="mt-2"><PluginTrustBadges trust={current.trust} warning /></div>{current.trust?.reviewed && <p className="mt-2 text-xs leading-5 text-muted-foreground">Registry reviewed는 배포 승인 절차를 통과했다는 뜻이며, 플러그인의 안전성이나 샌드박스를 의미하지 않습니다.</p>}</div><div className="mt-4 border-t border-border pt-3"><p className="text-xs font-semibold">기능</p><div className="mt-2 flex flex-wrap gap-1.5">{descriptor?.capabilities?.map(cap => <Badge key={cap} tone="blue">{cap}</Badge>) ?? <span className="text-xs text-muted-foreground">미보고</span>}</div></div><div className="mt-3"><p className="text-xs font-semibold">미디어 형식</p><div className="mt-2 flex flex-wrap gap-1.5">{descriptor?.media_types.map(type => <Badge key={type}>{type}</Badge>)}</div></div></CardContent></Card><div className="space-y-4"><Card><CardHeader><CardTitle>실행 상태</CardTitle></CardHeader><CardContent><StatusBadge state={current.status.state} />{current.status.error && <p className="mt-3 flex items-start gap-2 rounded-md bg-amber-500/10 p-3 text-xs leading-5 text-amber-800 dark:text-amber-200"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0" />{current.status.error}</p>}<p className="mt-3 text-xs text-muted-foreground">어댑터는 네이티브 실행 파일이며 Core와 같은 OS 사용자 권한으로 실행됩니다. 샌드박스는 제공되지 않습니다.</p></CardContent></Card><Card><CardHeader><CardTitle>리소스 유형 선언</CardTitle></CardHeader><CardContent>{allResourceTypes.length ? <div className="space-y-2">{allResourceTypes.map(item => <div key={item.type} className="rounded-md border border-border p-2.5"><p className="font-mono text-sm">{item.type}</p><p className="mt-1 text-xs text-muted-foreground">허용 상위 유형: {item.parent_types?.join(', ') || '없음'}</p></div>)}</div> : <p className="text-sm text-muted-foreground">리소스 유형을 선언하지 않았습니다.</p>}</CardContent></Card></div></div>}
    {tab === 'settings' && <div role="tabpanel" id="adapter-panel-settings" aria-labelledby="adapter-tab-settings" tabIndex={0} className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_330px]"><Card><CardHeader><CardTitle>어댑터 설정</CardTitle><p className="text-sm text-muted-foreground">입력 종류와 제약 조건은 어댑터 스키마가 선언합니다. 비밀 값은 되돌려 표시하지 않습니다.</p></CardHeader><CardContent>{config.isLoading ? <LoadingState /> : config.error || !config.data ? <ErrorState message={config.error ? errorMessage(config.error) : '설정을 불러올 수 없습니다.'} retry={() => void config.refetch()} /> : config.data.schema.fields.length ? <SchemaForm schema={config.data.schema} initialValues={config.data.effective.values} storedValues={config.data.stored.values} initialSecrets={config.data.effective.secrets} valueSources={config.data.value_sources} secretSources={config.data.secret_sources} mode="config" submitLabel="설정 저장" onSubmit={result => save.mutate({ values: result.values, secrets: result.secrets, clear_values: result.clearValues, clear_secrets: result.clearSecrets })} busy={save.isPending} /> : <EmptyState title="설정 가능한 항목이 없습니다." />}</CardContent></Card><div className="space-y-4"><ConfigScopeSelector adapterId={adapterId} resource={resource} onSelect={setResource} canBrowse={canBrowse} /></div></div>}
    {tab === 'resources' && canBrowse && <Card role="tabpanel" id="adapter-panel-resources" aria-labelledby="adapter-tab-resources" tabIndex={0}><CardHeader><CardTitle>리소스 탐색</CardTitle><p className="text-sm text-muted-foreground">Core는 리소스 유형과 ID의 의미를 해석하지 않습니다.</p></CardHeader><CardContent><ResourceBreadcrumbs resource={resource} onNavigate={setResource} /><div className="grid gap-2 sm:grid-cols-[1fr_190px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={q} onChange={event => setQ(event.target.value)} onKeyDown={event => event.key === 'Enter' && setSearchTerm(q)} placeholder="리소스 이름 검색" /></div><Input value={resourceType} onChange={event => setResourceType(event.target.value)} placeholder="리소스 유형" /><Button onClick={() => setSearchTerm(q)}><Search className="h-4 w-4" />검색</Button></div>{resource && <p className="mt-3 text-xs text-muted-foreground">상위 범위: {resourceLabel(resource)}</p>}{resources.isLoading ? <LoadingState /> : resources.error ? <ErrorState message={errorMessage(resources.error)} retry={() => void resources.refetch()} /> : resourceItems.length ? <div className="mt-4 divide-y divide-border">{resourceItems.map((item, index) => <div key={`${item.resource_type}-${item.resource_id}-${index}`} className="flex flex-wrap items-center gap-3 py-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.display_name ?? item.resource_id}</p><p className="mt-1 truncate font-mono text-xs text-muted-foreground">{item.resource_type} / {item.resource_id}</p>{item.parent && <p className="mt-1 truncate text-[10px] text-muted-foreground">상위 리소스: {resourceLabel(item.parent)}</p>}</div><Button variant="outline" size="sm" onClick={() => setResource({ resource_type: item.resource_type, resource_id: item.resource_id, parent: item.parent })}>하위 리소스 탐색</Button><Button size="sm" onClick={() => { setResource({ resource_type: item.resource_type, resource_id: item.resource_id, parent: item.parent }); setTab('settings') }}>이 범위 설정</Button></div>)}</div> : <EmptyState title="표시할 리소스가 없습니다." description="어댑터가 결과를 반환하지 않았거나 검색 결과가 없습니다." />}{resources.hasNextPage && <Button variant="outline" size="sm" className="mt-3" onClick={() => void resources.fetchNextPage()} disabled={resources.isFetchingNextPage}>{resources.isFetchingNextPage ? '불러오는 중…' : '더 보기'}</Button>}</CardContent></Card>}
    {tab === 'workflows' && <Card role="tabpanel" id="adapter-panel-workflows" aria-labelledby="adapter-tab-workflows" tabIndex={0}><CardHeader><CardTitle>어댑터 워크플로</CardTitle><p className="text-sm text-muted-foreground">활성 워크플로는 어댑터 프로세스 세대에 연결됩니다.</p></CardHeader><CardContent>{adapterWorkflows.length ? <div className="divide-y divide-border">{adapterWorkflows.map(workflow => <Link key={workflow.workflow_id} to="/workflows/$workflowId" params={{ workflowId: workflow.workflow_id }} className="flex items-center justify-between gap-3 py-3"><span><span className="block text-sm font-medium">{workflow.workflow_id}</span><span className="mt-1 block text-xs text-muted-foreground">{workflowStateLabel(workflow.state)} · 만료 {formatDate(workflow.expires_at)}</span></span><StatusBadge state={workflow.state} /></Link>)}</div> : <EmptyState title="활성 워크플로가 없습니다." />}</CardContent></Card>}
  </div>
}
function Info({ label, value }: { label: string; value: string | number }) { return <div><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-1 break-all text-sm font-medium">{value}</p></div> }
function ConfigScopeSelector({ adapterId, resource, onSelect, canBrowse }: { adapterId: string; resource?: ResourceRef; onSelect: (resource?: ResourceRef) => void; canBrowse: boolean }) {
  const [q, setQ] = useState(''); const [search, setSearch] = useState(''); const [resourceType, setResourceType] = useState('')
  const query = useQuery({ queryKey: qk.resources(adapterId, { search, resourceType }), queryFn: () => adaptersAPI.resources(adapterId, { q: search || undefined, resource_type: resourceType || undefined, limit: 20 }), enabled: Boolean(canBrowse && search.length >= 2), retry: false })
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-4 w-4" />설정 범위</CardTitle><p className="text-xs text-muted-foreground">현재 편집 범위: {resource ? resourceLabel(resource) : '어댑터 공통'}</p></CardHeader><CardContent><Button variant={!resource ? 'secondary' : 'outline'} size="sm" onClick={() => onSelect(undefined)}>어댑터 공통 범위</Button>{canBrowse && <><div className="mt-3 flex gap-2"><Input value={q} onChange={event => setQ(event.target.value)} placeholder="리소스 검색" aria-label="설정 범위 검색" /><Button variant="outline" size="sm" onClick={() => setSearch(q)}>검색</Button></div><Input className="mt-2" value={resourceType} onChange={event => setResourceType(event.target.value)} placeholder="리소스 유형 (선택)" aria-label="리소스 유형" />{query.data?.items.map((item: Resource, index: number) => <button key={`${item.resource_type}-${item.resource_id}-${index}`} className="mt-2 block w-full rounded-md border border-border p-2 text-left hover:bg-muted" onClick={() => onSelect({ resource_type: item.resource_type, resource_id: item.resource_id, parent: item.parent })}><span className="block truncate text-xs font-medium">{item.display_name ?? item.resource_id}</span><span className="block truncate text-[10px] text-muted-foreground">{item.resource_type}</span></button>)}</>}<p className="mt-3 text-[11px] leading-5 text-muted-foreground">다른 범위에서 상속된 값은 표시되며, 변경하면 이 범위에 재정의 값이 저장됩니다.</p></CardContent></Card>
}
