import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowRight, HardDrive, Radio, Video, Waves } from 'lucide-react'
import { Link } from '@tanstack/react-router'
import { dashboardAPI, recordingsAPI } from '@/api'
import { adaptersQuery, dashboardQuery, qk } from '@/api/queries'
import { formatBytes, formatDate, formatDuration, resourceLabel } from '@/lib/utils'
import { PageHeading } from '@/components/page-heading'
import { errorMessage } from '@/lib/errors'
import { StatusBadge } from '@/components/status-badge'
import { AdapterMark } from '@/components/adapter/adapter-mark'
import { PreviewThumbnail } from '@/components/recording/previews'
import { RecordingTitle } from '@/components/recording/list-identity'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Confirm } from '@/components/ui/confirm'
import { LoadingState, ErrorState, EmptyState } from '@/components/query-state'
import { useToast } from '@/components/ui/use-toast'
import type { RecordingSummary } from '@/types/api'
import { WatchSummary } from '@/components/watch/watch-summary'
import { useI18n } from '@/i18n/provider'

export function DashboardPage() {
  const client = useQueryClient(); const { toast } = useToast()
  const { t } = useI18n()
  const dash = useQuery(dashboardQuery); const adapters = useQuery(adaptersQuery); const storage = useQuery({ queryKey: qk.storage, queryFn: dashboardAPI.storage, staleTime: 30_000 })
  const stop = useMutation({ mutationFn: recordingsAPI.stop, onSuccess: () => { toast(t('dashboard.stop')); void client.invalidateQueries({ queryKey: qk.dashboard }); void client.invalidateQueries({ queryKey: ['recordings'] }) }, onError: error => toast(t('dashboard.stop'), errorMessage(error), 'error') })
  if (dash.isLoading) return <LoadingState label={t('dashboard.loading')} />
  if (dash.error || !dash.data) return <ErrorState message={errorMessage(dash.error)} retry={() => void dash.refetch()} />
  const data = dash.data
  const primaryMetrics = [
    [t('dashboard.metric.active'), data.active_recordings_count, Radio, 'text-emerald-600'], [t('dashboard.metric.total'), data.recordings_total, Waves, 'text-violet-600'],
    [t('dashboard.metric.archive'), data.archive_bytes_known === false ? '—' : formatBytes(data.archive_bytes), HardDrive, 'text-slate-600'], [t('dashboard.metric.completed24h'), data.completed_last_24h, Video, 'text-primary'],
  ] as const
  const healthMetrics = [
    [t('dashboard.metric.interrupted24h'), data.interrupted_last_24h], [t('dashboard.metric.adapterReady'), `${data.adapters.ready ?? 0} / ${data.adapters.total ?? 0}`],
    [t('dashboard.metric.integrityVerified'), data.integrity.verified ?? 0], [t('dashboard.metric.integrityIssues'), (data.integrity.degraded ?? 0) + (data.integrity.failed ?? 0)],
  ] as const
  const adapterByID = new Map((adapters.data ?? []).map(adapter => [adapter.status.id, adapter]))
  return <div className="page-enter"><PageHeading eyebrow={t('dashboard.eyebrow')} title={t('dashboard.title')} description={t('dashboard.description')} actions={<Link to="/new"><Button><Video className="h-4 w-4" />{t('nav.newRecording')}</Button></Link>} />
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{primaryMetrics.map(([label, value, Icon, color]) => <Card key={label}><CardContent className="flex min-h-[104px] items-start justify-between gap-3 pt-4"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight tabular-nums">{value}</p></div><span className={`rounded-md bg-muted p-2 ${color}`}><Icon className="h-4 w-4" /></span></CardContent></Card>)}</div>
    <div className="mt-2 grid grid-cols-2 gap-x-5 gap-y-2 rounded-lg border border-border bg-card px-4 py-3 sm:grid-cols-4">{healthMetrics.map(([label, value]) => <div key={label} className="flex min-w-0 items-baseline justify-between gap-2"><span className="truncate text-xs text-muted-foreground">{label}</span><span className="shrink-0 text-sm font-semibold tabular-nums">{value}</span></div>)}</div>
    {data.watches && <div className="mt-3"><WatchSummary summary={data.watches} /></div>}
    <div className="mt-5 grid gap-4 xl:grid-cols-[1.55fr_1fr]">
      <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>{t('dashboard.active.title')}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{t('dashboard.active.description')}</p></div><Link to="/recordings" search={{ state: 'recording' }} className="text-xs font-medium text-primary">{t('common.viewAll')} <ArrowRight className="inline h-3 w-3" /></Link></CardHeader><CardContent className="space-y-2">{data.active_recordings.length ? data.active_recordings.map(recording => <ActiveRow key={recording.id} recording={recording} adapter={adapterByID.get(recording.adapter_id ?? '')} onStop={() => stop.mutate(recording.id)} busy={stop.isPending} />) : <EmptyState title={t('dashboard.empty.active')} description={t('dashboard.empty.activeHelp')} />}</CardContent></Card>
      <Card><CardHeader><CardTitle>{t('dashboard.adapters.title')}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{t('dashboard.adapters.description')}</p></CardHeader><CardContent className="space-y-3">{adapters.data?.length ? adapters.data.map(adapter => <Link key={adapter.status.id} to="/adapters/$adapterId" params={{ adapterId: adapter.status.id }} search={{ tab: undefined }} className="flex min-w-0 items-center gap-3 rounded-md px-2 py-2 hover:bg-muted/60"><AdapterMark adapter={adapter} size="sm" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{adapter.descriptor?.name ?? adapter.status.name ?? adapter.status.id}</span><span className="block truncate text-xs text-muted-foreground">{adapter.status.id} · v{adapter.descriptor?.version ?? adapter.status.version ?? '—'}</span></span><StatusBadge state={adapter.status.state} /></Link>) : adapters.isLoading ? <LoadingState /> : <EmptyState title={t('dashboard.empty.plugins')} description={t('dashboard.empty.pluginsHelp')} />}</CardContent></Card>
    </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
      <Card className="min-w-0"><CardHeader className="flex-row items-center justify-between"><CardTitle>{t('dashboard.recent.title')}</CardTitle><Link to="/recordings" className="text-xs font-medium text-primary">{t('dashboard.recent.open')} <ArrowRight className="inline h-3 w-3" /></Link></CardHeader><CardContent className="min-w-0 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-border text-[11px] text-muted-foreground"><th className="pb-2 font-medium">{t('dashboard.table.state')}</th><th className="pb-2 font-medium">{t('dashboard.table.title')}</th><th className="pb-2 font-medium">{t('dashboard.table.source')}</th><th className="pb-2 text-right font-medium">{t('dashboard.table.started')}</th><th className="pb-2 text-right font-medium">{t('dashboard.table.segments')}</th></tr></thead><tbody>{data.recent_recordings.map(recording => <tr key={recording.id} className="border-b border-border/60 last:border-0"><td className="py-3"><StatusBadge state={recording.state} /></td><td className="max-w-[290px] py-3"><RecordingTitle recordingId={recording.id} title={recording.title} preview={recording.preview} adapterId={recording.adapter_id} adapterName={recording.adapter?.name} adapter={adapterByID.get(recording.adapter_id ?? '')} /></td><td className="max-w-48 py-3"><div className="flex min-w-0 items-center gap-2"><AdapterMark adapter={adapterByID.get(recording.adapter_id ?? '')} adapterId={recording.adapter_id} name={recording.adapter?.name} size="xs" /><span className="min-w-0"><span className="block truncate text-xs">{adapterByID.get(recording.adapter_id ?? '')?.descriptor?.name ?? recording.adapter?.name ?? recording.adapter_id ?? '—'}</span><span className="block truncate text-[11px] text-muted-foreground">{resourceLabel(recording.resource)}</span></span></div></td><td className="py-3 text-right text-xs text-muted-foreground">{formatDate(recording.started_at)}</td><td className="py-3 text-right tabular-nums">{recording.segment_count ?? 0}</td></tr>)}</tbody></table>{!data.recent_recordings.length && <EmptyState title={t('dashboard.empty.recordings')} />}</CardContent></Card>
      <Card><CardHeader><CardTitle>{t('nav.storage')}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{t('dashboard.storage.description')}</p></CardHeader><CardContent><div className="flex items-baseline justify-between"><span className="text-2xl font-semibold">{storage.data?.recordings_bytes_known === false || (storage.data?.recordings_bytes == null && data.archive_bytes_known === false) ? '—' : formatBytes(storage.data?.recordings_bytes ?? data.archive_bytes)}</span><span className="text-xs text-muted-foreground">{t('dashboard.storage.archive')}</span></div><progress className="storage-progress mt-4" value={data.filesystem_used_bytes} max={data.filesystem_total_bytes || 1} aria-label={t('dashboard.storage.used')} /><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><StorageStat label={t('dashboard.storage.used')} value={formatBytes(data.filesystem_used_bytes)} /><StorageStat label={t('dashboard.storage.available')} value={formatBytes(data.filesystem_free_bytes)} /><StorageStat label={t('dashboard.storage.total')} value={formatBytes(data.filesystem_total_bytes)} /><StorageStat label={t('dashboard.storage.recordings')} value={storage.data?.recording_count ?? data.recordings_total} /></div><Link to="/storage" className="mt-4 inline-block text-xs font-medium text-primary">{t('dashboard.storage.details')} <ArrowRight className="inline h-3 w-3" /></Link></CardContent></Card>
    </div>
  </div>
}
function StorageStat({ label, value }: { label: string; value: string | number }) { return <div><p className="text-muted-foreground">{label}</p><p className="mt-1 font-medium tabular-nums">{value}</p></div> }
function ActiveRow({ recording, onStop, busy, adapter }: { recording: RecordingSummary; onStop: () => void; busy: boolean; adapter?: import('@/types/api').Adapter }) { const { t } = useI18n(); return <div className="flex min-w-0 flex-wrap items-center gap-3 rounded-md border border-border/70 px-3 py-3"><StatusBadge state={recording.state} /><span className="relative shrink-0"><PreviewThumbnail recordingId={recording.id} summary={recording.preview} adapter={adapter} adapterId={recording.adapter_id} adapterName={recording.adapter?.name} className="w-16" /><span className="absolute -right-0.5 -top-0.5 h-2 w-2 animate-pulse rounded-full bg-emerald-500 ring-2 ring-card" /></span><div className="min-w-0 flex-1"><Link to="/recordings/$recordingId" params={{ recordingId: recording.id }} className="block truncate text-sm font-medium hover:text-primary" title={recording.title}>{recording.title || t('recordings.noTitle')}</Link><p className="mt-1 truncate text-xs text-muted-foreground">{adapter?.descriptor?.name ?? recording.adapter?.name ?? recording.adapter_id ?? '—'} · {resourceLabel(recording.resource)}</p></div><div className="hidden shrink-0 text-right sm:block"><p className="text-sm tabular-nums">{formatDuration(recording.duration_seconds)}</p><p className="text-[11px] text-muted-foreground">{t('timeline.segmentCount', { count: recording.segment_count ?? 0 })} · {t('recordings.gapsCount', { count: recording.gap_count ?? 0 })}</p></div><Confirm trigger={<Button variant="outline" size="sm">{t('dashboard.stop')}</Button>} title={t('dashboard.empty.stopTitle')} description={t('dashboard.empty.stopDescription')} confirmLabel={t('dashboard.empty.stopAction')} onConfirm={onStop} disabled={busy} /></div> }
